import { describe, it, expect } from 'vitest'
import { parse as yamlParse } from 'yaml'
import { configToYaml } from '../yaml-export.js'
import { GENERATOR_VERSION } from '../version.js'
import type { LovelaceConfig } from '../lovelace-config.js'

const sampleConfig: LovelaceConfig = {
  title: 'Lovelacer — Home',
  views: [
    {
      type: 'sections',
      title: 'Home',
      path: 'home',
      icon: 'mdi:home-variant',
      sections: [],
    },
    {
      type: 'sections',
      title: 'Kitchen',
      path: 'kitchen',
      icon: 'mdi:silverware-fork-knife',
      sections: [],
    },
  ],
}

function bodyAfterHeader(yaml: string): string {
  // Header is exactly 3 comment lines + 1 blank line. Drop them so the
  // remaining string is pure YAML for parsing.
  const lines = yaml.split('\n')
  return lines.slice(4).join('\n')
}

describe('configToYaml', () => {
  it('returns header + valid YAML for an empty config', () => {
    const empty: LovelaceConfig = { title: 'x', views: [] }
    const result = configToYaml(empty)
    expect(result).toContain('# Generated by Lovelacer')
    const parsed = yamlParse(bodyAfterHeader(result)) as LovelaceConfig
    expect(parsed).toEqual(empty)
  })

  it('round-trips a multi-view config via yaml.parse', () => {
    const result = configToYaml(sampleConfig)
    const parsed = yamlParse(bodyAfterHeader(result)) as LovelaceConfig
    expect(parsed).toEqual(sampleConfig)
  })

  it('pins the header format with explicit version and timestamp', () => {
    const result = configToYaml(sampleConfig, {
      version: 'test-1.2.3',
      generatedAt: new Date('2026-05-02T17:00:00.000Z'),
    })
    const lines = result.split('\n')
    expect(lines[0]).toBe('# Generated by Lovelacer vtest-1.2.3 on 2026-05-02T17:00:00.000Z')
    expect(lines[1]).toBe('# This file is regenerated each time you click Apply or Download YAML.')
    expect(lines[2]).toBe('# Manual edits to this file will NOT be preserved on the next run.')
    expect(lines[3]).toBe('')
  })

  it('uses GENERATOR_VERSION and a recent timestamp by default', () => {
    const before = Date.now()
    const result = configToYaml(sampleConfig)
    const after = Date.now()
    const firstLine = result.split('\n')[0]!
    expect(firstLine).toContain(`# Generated by Lovelacer v${GENERATOR_VERSION} on `)
    // Extract the ISO timestamp at the end of line 1 and verify it falls
    // within the test window. ISO 8601 length is fixed (24 chars).
    const tsMatch = firstLine.match(/on (\S+)$/)
    expect(tsMatch).not.toBeNull()
    const ts = new Date(tsMatch![1]!).getTime()
    expect(ts).toBeGreaterThanOrEqual(before)
    expect(ts).toBeLessThanOrEqual(after)
  })

  it('keeps long entity ids on a single line (lineWidth: 0)', () => {
    const longId = 'light.kitchen_under_cabinet_strip_with_a_very_long_name_indeed'
    const config: LovelaceConfig = {
      title: 'x',
      views: [
        {
          type: 'sections',
          title: 'K',
          path: 'k',
          icon: 'mdi:home',
          sections: [
            {
              type: 'grid',
              cards: [{ type: 'tile', entity: longId }],
            },
          ],
        },
      ],
    }
    const result = configToYaml(config)
    // The entity id appears exactly once and is not split across lines.
    const lines = result.split('\n')
    const linesContainingId = lines.filter((line) => line.includes(longId))
    expect(linesContainingId).toHaveLength(1)
    // The line containing the id should NOT contain a trailing backslash
    // or a YAML continuation marker — meaning the value isn't wrapped.
    expect(linesContainingId[0]).not.toMatch(/\\$/)
  })
})
