import { describe, it, expect, vi } from 'vitest'
import { parse as yamlParse } from 'yaml'
import type { HaClient } from '@lovelacer/ha-client'
import { englishCluttered } from '../../../../../tests/fixtures/english-cluttered.js'
import { fixtureToHaRegistries } from '../../../../../tests/fixtures/_builder/index.js'
import { createApp } from '../../app.js'
import { AppliedSnapshotStore } from '../../storage/applied-snapshot-store.js'
import { InviteStore } from '../../storage/invite-store.js'
import { OverrideStore } from '../../storage/override-store.js'

function makeStore(): OverrideStore {
  return new OverrideStore(':memory:')
}

function makeAcceptedInvite(): InviteStore {
  const s = new InviteStore(':memory:')
  s.accept('BETA-2026-ALPHA')
  return s
}

function makeAppliedSnapshot(): AppliedSnapshotStore {
  return new AppliedSnapshotStore(':memory:')
}

function makeHa(connected = true): HaClient {
  const ha = fixtureToHaRegistries(englishCluttered)
  return {
    isConnected: () => connected,
    getEntityRegistry: vi.fn(async () => ha.entities),
    getDeviceRegistry: vi.fn(async () => ha.devices),
    getAreaRegistry: vi.fn(async () => ha.areas),
    getFloorRegistry: vi.fn(async () => []),
  } as unknown as HaClient
}

describe('GET /api/export.yaml', () => {
  it('returns 503 ha_unavailable when HA is disconnected', async () => {
    const app = await createApp({
      ha: makeHa(false),
      overrides: makeStore(),
      invite: makeAcceptedInvite(),
      appliedSnapshot: makeAppliedSnapshot(),
      logLevel: 'silent',
      dashboardUrlPath: 'lovelacer-home',
    })
    try {
      const res = await app.inject({ method: 'GET', url: '/api/export.yaml' })
      expect(res.statusCode).toBe(503)
      expect(res.json()).toMatchObject({ error: 'ha_unavailable' })
    } finally {
      await app.close()
    }
  })

  it('returns 200 with valid YAML body and the right headers', async () => {
    const app = await createApp({
      ha: makeHa(true),
      overrides: makeStore(),
      invite: makeAcceptedInvite(),
      appliedSnapshot: makeAppliedSnapshot(),
      logLevel: 'silent',
      dashboardUrlPath: 'lovelacer-home',
    })
    try {
      const res = await app.inject({ method: 'GET', url: '/api/export.yaml' })
      expect(res.statusCode).toBe(200)
      expect(res.headers['content-type']).toBe('application/yaml; charset=utf-8')
      expect(res.headers['content-disposition']).toBe('attachment; filename="lovelacer-home.yaml"')
      expect(res.headers['x-content-type-options']).toBe('nosniff')
      // Body parses as YAML and has the expected top-level shape.
      const body = res.body
      expect(body).toContain('# Generated by Lovelacer')
      const lines = body.split('\n')
      const yamlBody = lines.slice(4).join('\n')
      const parsed = yamlParse(yamlBody) as { title: unknown; views: unknown[] }
      expect(typeof parsed.title).toBe('string')
      expect(Array.isArray(parsed.views)).toBe(true)
      expect(parsed.views.length).toBeGreaterThan(0)
    } finally {
      await app.close()
    }
  })

  it('returns 500 export_failed when the registry fetch throws', async () => {
    const ha = {
      isConnected: () => true,
      getEntityRegistry: vi.fn(async () => {
        throw new Error('boom')
      }),
      getDeviceRegistry: vi.fn(async () => []),
      getAreaRegistry: vi.fn(async () => []),
      getFloorRegistry: vi.fn(async () => []),
    } as unknown as HaClient
    const app = await createApp({
      ha,
      overrides: makeStore(),
      invite: makeAcceptedInvite(),
      appliedSnapshot: makeAppliedSnapshot(),
      logLevel: 'silent',
      dashboardUrlPath: 'lovelacer-home',
    })
    try {
      const res = await app.inject({ method: 'GET', url: '/api/export.yaml' })
      expect(res.statusCode).toBe(500)
      expect(res.json()).toMatchObject({ error: 'export_failed' })
    } finally {
      await app.close()
    }
  })

  it('uses dashboardUrlPath for the Content-Disposition filename', async () => {
    const app = await createApp({
      ha: makeHa(true),
      overrides: makeStore(),
      invite: makeAcceptedInvite(),
      appliedSnapshot: makeAppliedSnapshot(),
      logLevel: 'silent',
      dashboardUrlPath: 'my-dash',
    })
    try {
      const res = await app.inject({ method: 'GET', url: '/api/export.yaml' })
      expect(res.statusCode).toBe(200)
      expect(res.headers['content-disposition']).toBe('attachment; filename="my-dash.yaml"')
    } finally {
      await app.close()
    }
  })

  it('falls back to lovelacer-home.yaml when dashboardUrlPath is unsafe', async () => {
    // dashboardUrlPath would normally be validated by HA's storage-mode
    // schema upstream; this exercises the route's defense-in-depth fallback
    // for hypothetical future schema loosening.
    const app = await createApp({
      ha: makeHa(true),
      overrides: makeStore(),
      invite: makeAcceptedInvite(),
      appliedSnapshot: makeAppliedSnapshot(),
      logLevel: 'silent',
      dashboardUrlPath: '../etc/passwd',
    })
    try {
      const res = await app.inject({ method: 'GET', url: '/api/export.yaml' })
      expect(res.statusCode).toBe(200)
      expect(res.headers['content-disposition']).toBe('attachment; filename="lovelacer-home.yaml"')
    } finally {
      await app.close()
    }
  })
})
