name: Lovelacer
version: '0.4.15'
slug: lovelacer
description: Generate a Lovelace dashboard from your Home Assistant entities
url: https://github.com/Studio81Labs/lovelacer
arch:
  - aarch64
  - amd64
init: false
ingress: true
ingress_port: 3000
panel_icon: mdi:home-variant
panel_title: Lovelacer
homeassistant_api: true
hassio_api: false
host_network: false
apparmor: true
options:
  log_level: info
  dashboard_url_path: lovelacer-home
schema:
  log_level: list(trace|debug|info|warn|error|fatal)
  dashboard_url_path: match(^[a-z0-9][a-z0-9-]*$)
image: ghcr.io/studio81labs/lovelacer-{arch}
