<script setup lang="ts">
import ThemedScreenshot from './ThemedScreenshot.vue'

interface Props {
  variant?: 'hero' | 'section'
}
const props = withDefaults(defineProps<Props>(), { variant: 'hero' })
</script>

<template>
  <section :class="['lc-beforeafter', `lc-beforeafter--${props.variant}`]">
    <div class="lc-section lc-section--wide">
      <div v-if="props.variant === 'hero'" class="lc-beforeafter__head">
        <p class="lc-eyebrow">See the difference</p>
        <h1 class="lc-display lc-beforeafter__title">
          Same Home Assistant install.<br />
          One <em>worth</em> looking at.
        </h1>
        <p class="lc-beforeafter__lede">
          Home Assistant generates a default dashboard that dumps every entity into a single view.
          Lovelacer reads your registry, infers rooms, and produces a dashboard organized like a
          home — one tab per room, cards grouped by what they do.
        </p>
        <div class="lc-cta-row" style="margin-top: 2rem">
          <a class="lc-btn lc-btn--primary" href="/docs/install/supervised"
            >Install on Home Assistant</a
          >
          <a class="lc-btn lc-btn--ghost" href="#how-it-works">How it works</a>
        </div>
      </div>

      <div v-else class="lc-beforeafter__head">
        <p class="lc-eyebrow">The shape of the change</p>
        <h2 class="lc-display lc-beforeafter__title lc-beforeafter__title--section">
          A picture saves a lot of <em>words</em>.
        </h2>
      </div>

      <div class="lc-beforeafter__panels">
        <figure class="lc-beforeafter__panel">
          <figcaption class="lc-beforeafter__caption">
            <span class="lc-pill lc-pill--neutral">Before</span>
            <span>HA's auto-generated dashboard</span>
          </figcaption>
          <img
            src="/screenshots/before-ha-default.png"
            alt="Home Assistant's default auto-generated dashboard showing a wall of cryptic entity IDs with no grouping"
            class="lc-screenshot"
            loading="lazy"
          />
        </figure>

        <div class="lc-beforeafter__arrow" aria-hidden="true">→</div>

        <figure class="lc-beforeafter__panel">
          <figcaption class="lc-beforeafter__caption">
            <span class="lc-pill lc-pill--success">After</span>
            <span>Generated by Lovelacer</span>
          </figcaption>
          <ThemedScreenshot
            name="ha-jidelna"
            alt="A clean Lovelacer-generated Home Assistant dashboard view (Jídelna) with lights, climate, and other sensors organized in three columns"
          />
        </figure>
      </div>

      <p v-if="props.variant === 'hero'" class="lc-beforeafter__footnote">
        Real screenshots from a Czech HA install. Your dashboard will use your own room names and
        language.
      </p>
    </div>
  </section>
</template>

<style scoped>
.lc-beforeafter--hero {
  padding-top: 1rem;
}

.lc-beforeafter__head {
  max-width: 720px;
  margin-bottom: 3rem;
}

.lc-beforeafter__title {
  font-size: clamp(2.5rem, 5vw, 4rem);
  margin-bottom: 1.5rem;
}

.lc-beforeafter__title--section {
  font-size: clamp(2rem, 3.5vw, 2.75rem);
  margin-bottom: 0;
}

.lc-beforeafter__lede {
  font-size: 1.125rem;
  line-height: 1.6;
  color: var(--vp-c-text-2);
  max-width: 620px;
}

.lc-beforeafter__panels {
  display: grid;
  grid-template-columns: 1fr auto 1fr;
  gap: 1.5rem;
  align-items: center;
}

@media (max-width: 880px) {
  .lc-beforeafter__panels {
    grid-template-columns: 1fr;
  }
  .lc-beforeafter__arrow {
    transform: rotate(90deg);
    text-align: center;
  }
}

.lc-beforeafter__panel {
  margin: 0;
}

.lc-beforeafter__caption {
  display: flex;
  align-items: center;
  gap: 0.625rem;
  margin-bottom: 0.875rem;
  font-size: 0.875rem;
  color: var(--vp-c-text-2);
}

.lc-beforeafter__arrow {
  font-family: var(--lc-font-display);
  font-size: 2.5rem;
  color: var(--lc-amber-500);
  font-style: italic;
  text-align: center;
  padding: 0 0.5rem;
}
.dark .lc-beforeafter__arrow {
  color: var(--lc-amber-300);
}

.lc-beforeafter__footnote {
  margin-top: 2rem;
  font-size: 0.875rem;
  color: var(--vp-c-text-3);
  text-align: center;
}
</style>
