<script setup lang="ts">
import ThemedScreenshot from './ThemedScreenshot.vue'

interface Props {
  variant?: 'hero' | 'section'
}
const props = withDefaults(defineProps<Props>(), {
  variant: 'hero',
})

const isSection = props.variant === 'section'
</script>

<template>
  <section :class="['lc-beforeafter', `lc-beforeafter--${props.variant}`]">
    <div class="lc-section lc-section--wide">
      <template v-if="isSection">
        <div class="lc-beforeafter__head">
          <p class="lc-eyebrow">The shape of the change</p>
          <h2 class="lc-display lc-beforeafter__title lc-beforeafter__title--section">
            A picture saves a lot of <em>words</em>.
          </h2>
        </div>

        <div class="lc-beforeafter__panels lc-beforeafter__panels--full">
          <figure class="lc-beforeafter__panel">
            <figcaption class="lc-beforeafter__caption">
              <span class="lc-pill lc-pill--neutral">Before</span>
              <span>HA's auto-generated dashboard</span>
            </figcaption>
            <img
              src="/screenshots/before-ha-default.png"
              alt="Home Assistant's default auto-generated dashboard showing a wall of cryptic entity IDs with no grouping"
              class="lc-screenshot"
              loading="lazy"
            />
          </figure>

          <div class="lc-beforeafter__arrow" aria-hidden="true">→</div>

          <figure class="lc-beforeafter__panel">
            <figcaption class="lc-beforeafter__caption">
              <span class="lc-pill lc-pill--success">After</span>
              <span>Generated by Lovelacer</span>
            </figcaption>
            <ThemedScreenshot
              name="ha-jidelna"
              alt="A clean Lovelacer-generated Home Assistant dashboard view (Jídelna) with lights, climate, and other sensors organized in three columns"
            />
          </figure>
        </div>
      </template>

      <template v-else>
        <div class="lc-beforeafter__grid">
          <div class="lc-beforeafter__text">
            <p class="lc-eyebrow">See the difference</p>
            <h1 class="lc-display lc-beforeafter__title">
              <span class="lc-beforeafter__desktop-title">Same Home Assistant install.</span>
              <span class="lc-beforeafter__mobile-title">Same Home Assistant<br />install.</span>
              <br />
              Organized like a <em>home</em>.
            </h1>
            <p class="lc-beforeafter__lede">
              Home Assistant exposes raw entities and integrations. Lovelacer reads your registry,
              infers rooms, and generates a clean dashboard you can preview before applying.
            </p>
            <div class="lc-cta-row">
              <a class="lc-btn lc-btn--primary" href="/docs/install/supervised">
                Install on Home Assistant
              </a>
              <a class="lc-btn lc-btn--ghost" href="#how-it-works">How it works</a>
            </div>
            <p class="lc-beforeafter__footnote">
              Real screenshots from a Czech Home Assistant install. Your dashboard will use your own
              rooms, entities, and language.
            </p>
          </div>

          <div class="lc-beforeafter__visual">
            <div class="lc-beforeafter__layered">
              <figure class="lc-beforeafter__layered-before">
                <span class="lc-pill lc-pill--neutral lc-beforeafter__layered-pill">Before</span>
                <img
                  src="/screenshots/before-ha-default.png"
                  alt="Home Assistant's default auto-generated dashboard"
                  class="lc-screenshot"
                  loading="eager"
                />
              </figure>
              <figure class="lc-beforeafter__layered-after">
                <span class="lc-pill lc-pill--success lc-beforeafter__layered-pill">After</span>
                <ThemedScreenshot
                  name="ha-jidelna"
                  alt="A clean Lovelacer-generated Home Assistant dashboard view"
                  loading="eager"
                />
              </figure>
            </div>
          </div>
        </div>
      </template>
    </div>
  </section>
</template>

<style scoped>
.lc-beforeafter--hero {
  overflow: clip;
  padding-top: 0.5rem;
}

.lc-beforeafter--hero .lc-section {
  padding-top: 4rem;
  padding-bottom: 2.5rem;
}

.lc-beforeafter__text {
  min-width: 0;
  max-width: 560px;
}

.lc-beforeafter__mobile-title {
  display: none;
}

.lc-beforeafter__head {
  max-width: 720px;
  margin-bottom: 3rem;
}

.lc-beforeafter__title {
  font-size: clamp(2.25rem, 4vw, 3.5rem);
  margin-bottom: 1.25rem;
  line-height: 1.05;
}

.lc-beforeafter__title--section {
  font-size: clamp(2rem, 3.5vw, 2.75rem);
  margin-bottom: 0;
}

.lc-beforeafter__lede {
  font-size: 1.0625rem;
  line-height: 1.55;
  color: var(--vp-c-text-2);
  margin: 0 0 1.5rem;
}

.lc-cta-row {
  display: flex;
  flex-wrap: wrap;
  gap: 0.75rem;
  margin: 0;
}

.lc-beforeafter__footnote {
  margin: 1.5rem 0 0;
  font-size: 0.8125rem;
  color: var(--vp-c-text-3);
  max-width: 480px;
}

.lc-beforeafter__grid {
  display: grid;
  grid-template-columns: minmax(0, 1fr) minmax(0, 1.15fr);
  gap: 3rem;
  align-items: center;
}

.lc-beforeafter__visual {
  min-width: 0;
}

.lc-beforeafter__layered {
  position: relative;
  width: 100%;
  aspect-ratio: 5 / 4;
  min-height: 380px;
}

.lc-beforeafter__layered-before,
.lc-beforeafter__layered-after {
  position: absolute;
  margin: 0;
  border-radius: 10px;
  overflow: hidden;
  box-shadow:
    0 20px 40px -16px rgba(0, 0, 0, 0.25),
    0 10px 24px -10px rgba(0, 0, 0, 0.15);
  outline: 1px solid var(--vp-c-divider);
  outline-offset: -1px;
}

.lc-beforeafter__layered-before {
  top: 0;
  left: 0;
  width: 60%;
  z-index: 1;
  transform: rotate(-3deg);
  transform-origin: bottom right;
  opacity: 0.85;
  filter: saturate(0.85);
}

.lc-beforeafter__layered-after {
  right: 0;
  bottom: 0;
  width: 78%;
  z-index: 2;
}

.lc-beforeafter__layered .lc-screenshot {
  display: block;
  width: 100%;
  height: auto;
}

.lc-beforeafter__layered-pill {
  position: absolute;
  top: 0.625rem;
  left: 0.625rem;
  z-index: 3;
  font-size: 0.75rem;
}

@media (max-width: 960px) {
  .lc-beforeafter__grid {
    grid-template-columns: 1fr;
    gap: 2.5rem;
  }

  .lc-beforeafter__layered {
    aspect-ratio: 4 / 3;
    min-height: 300px;
  }
}

@media (max-width: 640px) {
  .lc-beforeafter--hero .lc-section {
    padding-top: 2.5rem;
    padding-bottom: 2rem;
  }

  .lc-beforeafter__title {
    font-size: clamp(2.05rem, 10vw, 2.45rem);
  }

  .lc-beforeafter__desktop-title {
    display: none;
  }

  .lc-beforeafter__mobile-title {
    display: inline;
  }

  .lc-beforeafter__grid {
    gap: 1.5rem;
  }

  .lc-cta-row {
    display: grid;
    grid-template-columns: minmax(0, 1.45fr) minmax(0, 1fr);
  }

  .lc-btn {
    min-width: 0;
    padding: 0.65rem 0.75rem;
    font-size: 0.875rem;
  }

  .lc-beforeafter__footnote {
    display: none;
  }

  .lc-beforeafter__layered {
    aspect-ratio: 1.45 / 1;
    min-height: 220px;
  }

  .lc-beforeafter__layered-before {
    width: 72%;
  }

  .lc-beforeafter__layered-after {
    width: 88%;
  }
}

.lc-beforeafter__panels {
  margin: 0;
}

.lc-beforeafter__panels--full {
  display: grid;
  grid-template-columns: 1fr auto 1fr;
  gap: 1.5rem;
  align-items: center;
}

@media (max-width: 880px) {
  .lc-beforeafter__panels--full {
    grid-template-columns: 1fr;
  }

  .lc-beforeafter__panels--full .lc-beforeafter__arrow {
    transform: rotate(90deg);
    text-align: center;
  }
}

.lc-beforeafter__panel {
  margin: 0;
}

.lc-beforeafter__caption {
  display: flex;
  align-items: center;
  gap: 0.625rem;
  margin-bottom: 0.75rem;
  font-size: 0.8125rem;
  color: var(--vp-c-text-2);
}

.lc-beforeafter__arrow {
  font-family: var(--lc-font-display);
  font-size: 2.5rem;
  color: var(--lc-amber-500);
  font-style: italic;
  text-align: center;
  padding: 0 0.5rem;
}
.dark .lc-beforeafter__arrow {
  color: var(--lc-amber-300);
}
</style>
