import { stringify } from 'yaml'
import { GENERATOR_VERSION } from './index.js'
import type { LovelaceConfig } from './lovelace-config.js'

export interface ConfigToYamlOptions {
  /** Tool version printed in the header. Defaults to GENERATOR_VERSION. */
  version?: string
  /** Generation timestamp. Defaults to `new Date()` — caller can pin for tests. */
  generatedAt?: Date
}

/**
 * Serialize a LovelaceConfig as a YAML string with a minimal three-line
 * header comment. Stable output: same input + same options → byte-identical
 * string (modulo `generatedAt` if not pinned).
 *
 * `lineWidth: 0` disables yaml.stringify's default 80-char wrap so long
 * entity ids (e.g. `light.kitchen_under_cabinet_strip_with_a_very_long_name`)
 * stay on one line — visually cleaner and easier to grep.
 */
export function configToYaml(config: LovelaceConfig, options?: ConfigToYamlOptions): string {
  const version = options?.version ?? GENERATOR_VERSION
  const generatedAt = (options?.generatedAt ?? new Date()).toISOString()
  const header =
    `# Generated by Lovelacer v${version} on ${generatedAt}\n` +
    `# This file is regenerated each time you click Apply or Download YAML.\n` +
    `# Manual edits to this file will NOT be preserved on the next run.\n` +
    `\n`
  const body = stringify(config, {
    indent: 2,
    lineWidth: 0,
    minContentWidth: 0,
  })
  return header + body
}
