export interface AdminKeyword {
  language: string
  patterns: string[]
}

/**
 * Localized admin/maintenance keyword database.
 *
 * Patterns are pre-normalized for `normalizeForMatching()`: lowercase,
 * no diacritics, words separated by single spaces. Runtime matching
 * intentionally checks every language because real HA installs often mix
 * English integration names with localized user labels.
 */
export const ADMIN_KEYWORDS: AdminKeyword[] = [
  {
    language: 'en',
    patterns: [
      'rssi',
      'lqi',
      'link quality',
      'signal strength',
      'connection quality',
      'voltage',
      'voltmeter',
      'current',
      'power',
      'energy',
      'frequency',
      'radar sensitivity',
      'sensitivity',
      'minimum range',
      'maximum range',
      'min range',
      'max range',
      'detection delay',
      'fading time',
      'self test',
      'calibration',
      'calibrate',
      'temperature unit',
      'temp unit',
      'unit of measurement',
      'uptime',
      'firmware',
      'restart',
      'reboot',
    ],
  },
  {
    language: 'cs',
    patterns: [
      'citlivost',
      'minimalni rozsah',
      'maximalni rozsah',
      'min rozsah',
      'max rozsah',
      'zpozdeni detekce',
      'prodleva detekce',
      'doba dohasinani',
      'doba vyhasnuti',
      'samo test',
      'samotest',
      'vlastni test',
      'kalibrace',
      'kalibrovat',
      'jednotka teploty',
      'merna jednotka',
      'napeti',
      'voltmetr',
      'proud',
      'vykon',
      'energie',
      'frekvence',
      'sila signalu',
      'kvalita spojeni',
      'doba behu',
      'firmware',
      'restart',
      'restartovat',
    ],
  },
  {
    language: 'sk',
    patterns: [
      'citlivost',
      'minimalny rozsah',
      'maximalny rozsah',
      'min rozsah',
      'max rozsah',
      'oneskorenie detekcie',
      'doba zhasinania',
      'samo test',
      'samotest',
      'vlastny test',
      'kalibracia',
      'kalibrovat',
      'jednotka teploty',
      'merna jednotka',
      'napatie',
      'voltmeter',
      'prud',
      'vykon',
      'energia',
      'frekvencia',
      'sila signalu',
      'kvalita spojenia',
      'doba behu',
      'firmver',
      'firmware',
      'restart',
      'restartovat',
    ],
  },
  {
    language: 'de',
    patterns: [
      'empfindlichkeit',
      'mindestreichweite',
      'maximale reichweite',
      'min reichweite',
      'max reichweite',
      'erkennungsverzogerung',
      'verzogerung',
      'ausblendzeit',
      'selbsttest',
      'kalibrierung',
      'kalibrieren',
      'temperatureinheit',
      'masseinheit',
      'spannung',
      'voltmeter',
      'strom',
      'leistung',
      'energie',
      'frequenz',
      'signalstarke',
      'verbindungsqualitat',
      'laufzeit',
      'firmware',
      'neustart',
      'neu starten',
    ],
  },
]
