name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build-addon.yml
    secrets: inherit
    with:
      version: ${{ github.ref_name }}
      additional_tags: |
        latest
        ${{ github.ref_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          tag_name: ${{ github.ref_name }}
